//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCream.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FeedBack
    {
        public int ContactId { get; set; }
        public Nullable<int> CustomerId { get; set; }


        [Required(ErrorMessage = "Feedback subject is required")]
        [DisplayName("Feedback Subject")]
        [MaxLength(50, ErrorMessage = "Feedback subject contain maximum 50 characters")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Feedback content is required")]
        [DisplayName("Feedback Content")]
        [MaxLength(500, ErrorMessage = "Feedback content contain maximum 500 characters")]
        public string Content { get; set; }
    }
}
