//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCream.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetailBook
    {
        public int InvoiceDetailId { get; set; }
        public int ProductId { get; set; }
        public int InvoiceId { get; set; }
        public double SubTotal { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
