//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCream.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.InvoiceDetailBook = new HashSet<InvoiceDetailBook>();
        }
    
        public int InvoiceId { get; set; }
        [Required(ErrorMessage = "Customer Name is required")]
        [DisplayName("Customer Name")]
        [MaxLength(30, ErrorMessage = "Customer Name contain maximum 30 characters")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [DisplayName("Address Name")]
        [MaxLength(30, ErrorMessage = "Address delivery contain maximum 30 characters")]
        public string CustomerAddress { get; set; }


        public System.DateTime OrderDate { get; set; }
        public string Payment { get; set; }
        public bool OrderStatus { get; set; }
        public int Total { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetailBook> InvoiceDetailBook { get; set; }
    }
}
