//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCream.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoiceDetailBook = new HashSet<InvoiceDetailBook>();
        }

        public int ProductId { get; set; }
        public int CateId { get; set; }
        public int ManuId { get; set; }

        [Required(ErrorMessage = "Product Name is required")]
        [DisplayName("Product Name")]
        [MaxLength(50, ErrorMessage = "Product Name contain maximum 50 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Product Type is required")]
        [DisplayName("Product Type")]
        [MaxLength(50, ErrorMessage = "Product Type contain maximum 50 characters")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Recipe Date is required")]
        [DisplayName("Recipe Date")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public System.DateTime Date { get; set; }

        [Required(ErrorMessage = "Unit Price is required")]
        [DisplayName("Unit Price")]
        [Range(10, 1000, ErrorMessage = "Unit price must be between 10 and 1000")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [MaxLength(500, ErrorMessage = "Description contain maximum 500 characters")]
        public string Description { get; set; }

        [DisplayName("Product Image")]
        public string Image { get; set; }

        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetailBook> InvoiceDetailBook { get; set; }
    }
}
